version: 2

updates:
  # Keep GitHub Actions (including reusable workflows) up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    reviewers:
      - "your-username-here"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps): "
      include: "scope"
