name: Security Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security-scan:
    uses: renan-org/shared-security-scan/.github/workflows/security-scan.yml@v1.0.0
    with:
      scan-target: '.'
      upload-artifact: true
